# Generated by Django 3.2.5 on 2021-07-12 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210712_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 23, 9, 47, 760196, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
