# Generated by Django 3.2.5 on 2021-07-13 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 5, 49, 48, 207864, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
